version: '2'
services:
  myapp:
    image: spring-boot-docker:spring-docker
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8761:8761'
    expose:
      - 8761
    stdin_open: true
    tty: true