version: "3.8"
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SPRING_APPLICATION_JSON: '{
        "zuul.routes.partner.url" : "http://localhost:4040",
        "zuul.routes.main.url" : "http://localhost:3030",
        "server.port" : 8888,
        "spring.application.name" : "zuul-server",
        "eureka.instance.preferIpAddress" : true,
        "eureka.client.registerWithEureka" : true,
        "eureka.client.fetchRegistry" : true,
        "eureka.client.serviceUrl.defaultZone" :  "http://localhost:8761/eureka/" }'
    ports:
      - "8080:8080"
